### ISSUE TITLE
Promise在nodeJS和浏览器环境下的不同实现方案

### ISSUE THREAD

**Issue by slashhuang** [slashhuang/blog#6]
## Promise序言
> Promise对于前端界已经是个耳熟能详的概念了，然而它的真正原理和内部实现却有着深邃的精髓值得挖掘，本文就Promise在nodeJS和浏览器环境下的不同实现以及如何自己实现一个Promise进行了剖析讨论。

## 本文观点引用的官方资料
> [nodeJS对事件循环的处理说明](https://github.com/nodejs/node/blob/master/doc/topics/event-loop-timers-and-nexttick.md)
> [nodeJS对microTask、macroTask的说明]()

**Comment by slashhuang** [comment]
本文持续更新中

**Comment by FTAndy** [comment]
你也准备写一篇的咯？

**Comment by slashhuang** [comment]
是啊 @FTAndy ，话说我就是在知乎上喷你的那个人。
不过后来我看了你的实现。。。。蛮厉害的

**Comment by FTAndy** [comment]
我只是参考了几个 Promise 实现，然后自己模仿着思路写的，集大成者而已。

**Comment by slashhuang** [comment]
谦虚了。。看过代码，能过Promise test @FTAndy

**Comment by FTAndy** [comment]
能，肯定要过 Promise/A+ test，不然不能通用了。不过还有一个 [es6 test](https://github.com/promises-es6/promises-es6)。

**Comment by FTAndy** [comment]
@slashhuang 那个 simple-promise 是你同事写的吗？知乎上你给过链接

**Comment by slashhuang** [comment]
是我学弟。。他后来更新了代码，能跑过A+test，benchmark性能上能超过你写的那个，虽然还是跑不过官方then/promise的实现。

**Comment by FTAndy** [comment]
学生还是多时间搞啊，工作就没那么多时间了
